# Generated by Django 2.0 on 2020-12-15 18:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('voting', '0003_auto_20180605_0842'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidatura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField()),
                ('delegadoCentro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delegado_centro', to=settings.AUTH_USER_MODEL)),
                ('representanteDelegadoCuarto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='representante_cuarto', to=settings.AUTH_USER_MODEL)),
                ('representanteDelegadoMaster', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='representante_master', to=settings.AUTH_USER_MODEL)),
                ('representanteDelegadoPrimero', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='representante_primero', to=settings.AUTH_USER_MODEL)),
                ('representanteDelegadoSegundo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='representante_segundo', to=settings.AUTH_USER_MODEL)),
                ('representanteDelegadoTercero', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='representante_tercero', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
