# Generated by Django 2.0 on 2020-12-16 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0004_candidatura'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidatura',
            name='delegadoCentro',
        ),
        migrations.RemoveField(
            model_name='candidatura',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='candidatura',
            name='representanteDelegadoCuarto',
        ),
        migrations.RemoveField(
            model_name='candidatura',
            name='representanteDelegadoMaster',
        ),
        migrations.RemoveField(
            model_name='candidatura',
            name='representanteDelegadoPrimero',
        ),
        migrations.RemoveField(
            model_name='candidatura',
            name='representanteDelegadoSegundo',
        ),
        migrations.RemoveField(
            model_name='candidatura',
            name='representanteDelegadoTercero',
        ),
    ]
