# Generated by Django 2.0 on 2020-12-17 15:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VotingUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=9, unique=True, validators=[django.core.validators.RegexValidator(message='El formato debe ser 8 digitos y una letra mayuscula.', regex='^\\d{8}[A-Z]{1}$')])),
                ('sexo', models.CharField(choices=[('NONE', 'None'), ('HOMBRE', 'Hombre'), ('MUJER', 'Mujer'), ('OTRO', 'Otro')], default='NONE', max_length=6)),
                ('titulo', models.CharField(max_length=100)),
                ('curso', models.CharField(choices=[('PRIMERO', 'Primero'), ('SEGUNDO', 'Segundo'), ('TERCERO', 'Tercero'), ('CUARTO', 'Cuarto'), ('MASTER', 'Master')], default='PRIMERO', max_length=7)),
            ],
        ),
    ]
