# Generated by Django 2.0 on 2021-01-01 18:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20201230_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='votinguser',
            name='edad',
            field=models.PositiveIntegerField(default=10, validators=[django.core.validators.MinValueValidator(17), django.core.validators.MaxValueValidator(100)], verbose_name='age'),
        ),
    ]
