# Generated by Django 2.0 on 2021-01-01 19:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_votinguser_edad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votinguser',
            name='edad',
            field=models.PositiveIntegerField(default=18, validators=[django.core.validators.MinValueValidator(17), django.core.validators.MaxValueValidator(100)], verbose_name='age'),
        ),
        migrations.AlterField(
            model_name='votinguser',
            name='titulo',
            field=models.CharField(choices=[('SOFT', 'Software'), ('COMP', 'Computer Technology'), ('INFTECH', 'Information Technology'), ('HEALTH', 'Health')], default='SOFT', max_length=22, verbose_name='Grade'),
        ),
    ]
