# Generated by Django 2.0 on 2021-01-11 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_auto_20210101_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votinguser',
            name='sexo',
            field=models.CharField(choices=[('Man', 'Man'), ('Woman', 'Woman')], default='Woman', max_length=6, verbose_name='Gender'),
        ),
    ]
